/*
 * Copyright 2002-2018 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * <p>This package contains Spring's JSP standard tag library for JSP 2.0+.
 * Supports JSP view implementations within Spring's Web MVC framework.
 * For more details on each tag, see the list of tags below with links to
 * individual tag classes, or check the {@code spring.tld} file:
 *
 * <ul>
 * <li>{@link org.springframework.web.servlet.tags.ArgumentTag The argument tag}
 * <li>{@link org.springframework.web.servlet.tags.BindTag The bind tag}
 * <li>{@link org.springframework.web.servlet.tags.BindErrorsTag The hasBindErrors tag}
 * <li>{@link org.springframework.web.servlet.tags.EscapeBodyTag The escapeBody tag}
 * <li>{@link org.springframework.web.servlet.tags.EvalTag The eval tag}
 * <li>{@link org.springframework.web.servlet.tags.HtmlEscapeTag The htmlEscape tag}
 * <li>{@link org.springframework.web.servlet.tags.MessageTag The message tag}
 * <li>{@link org.springframework.web.servlet.tags.NestedPathTag The nestedPath tag}
 * <li>{@link org.springframework.web.servlet.tags.ParamTag The param tag}
 * <li>{@link org.springframework.web.servlet.tags.ThemeTag The theme tag}
 * <li>{@link org.springframework.web.servlet.tags.TransformTag The transform tag}
 * <li>{@link org.springframework.web.servlet.tags.UrlTag The url tag}
 * </ul>
 *
 * <p>Please note that the various tags generated by this form tag library are
 * compliant with http://www.w3.org/TR/xhtml1/ and attendant
 * http://www.w3.org/TR/xhtml1/dtds.html#a_dtd_XHTML-1.0-Strict.
 */
@NonNullApi
@NonNullFields
package org.springframework.web.servlet.tags;

import org.springframework.lang.NonNullApi;
import org.springframework.lang.NonNullFields;
